pool: 
  vmImage: 'windows-2019'

pr: none
  
trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - azure-pipelines.yml
    - README.md
    - CODE_OF_CONDUCT.md
    - SECURITY.md
    - LICENSE
    - .gitignore
    - .github/*
    - package
    - scratch.*

steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Install-Module Plaster,Pester,GuestConfiguration -force
    pwsh: false
  displayName: 'Install required modules'
  
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      mkdir '$(Build.SourcesDirectory)\GuestConfigurationProject'
      robocopy /e '$(Build.SourcesDirectory)\Modules' '$(Build.SourcesDirectory)\GuestConfigurationProject\Modules'
      robocopy /e '$(Build.SourcesDirectory)\test' '$(Build.SourcesDirectory)\GuestConfigurationProject\test'
      copy Configuration.mof $(Build.SourcesDirectory)\GuestConfigurationProject\'
      copy GestConfigurationProject.psd1 $(Build.SourcesDirectory)\GuestConfigurationProject\'
      copy LICENSE $(Build.SourcesDirectory)\GuestConfigurationProject\'
      copy plasterManifest.xml $(Build.SourcesDirectory)\GuestConfigurationProject\'
      copy project.code-workspace $(Build.SourcesDirectory)\GuestConfigurationProject\'

      $params = @{
        Path        = '$(Build.SourcesDirectory)'
        NuGetApiKey = '$(apikey)'
      }
      Get-ChildItem $(Build.SourcesDirectory)\GuestConfigurationProject\' -recurse
      
      #Publish-Module @params
    pwsh: false
  displayName: 'Publish to Gallery'
