pool: 
  vmImage: 'windows-2019'

pr: none
  
trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - azure-pipelines.yml
    - README.md
    - CODE_OF_CONDUCT.md
    - SECURITY.md
    - LICENSE
    - .gitignore
    - .github/*
    - package
    - scratch.*

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      ls '$(Build.SourcesDirectory)'
      Install-Module Plaster,Pester,GuestConfiguration -force
      $params = @{
        Path        = '$(Build.SourcesDirectory)'
        NuGetApiKey = '$(apikey)'
        ErrorAction = 'Stop'
      }
      Publish-Module @params -verbose
    pwsh: false
  displayName: 'Publish to Gallery on merge to Master'
