pool: 
  vmImage: 'windows-2019'

pr: none
  
trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - azure-pipelines.yml
    - README.md
    - CODE_OF_CONDUCT.md
    - SECURITY.md
    - LICENSE
    - .gitignore
    - .github/*
    - package
    - scratch.*

steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Install-Module Plaster,Pester,GuestConfiguration -force
    pwsh: false
  displayName: 'Install required modules'
  
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $params = @{
        Path        = '$(Build.SourcesDirectory)\GuestConfigurationProject'
        NuGetApiKey = '$(apikey)'
      }
      Publish-Module @params
    pwsh: false
  displayName: 'Publish to Gallery'
