pool: 
  vmImage: 'ubuntu-latest'

pr: none
  
trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - azure-pipelines.yml
    - README.md
    - CODE_OF_CONDUCT.md
    - SECURITY.md
    - LICENSE
    - .gitignore
    - .github/*
    - package
    - scratch.*

steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Install-Module Plaster,Pester,GuestConfiguration -force
    pwsh: false
  displayName: 'Install required modules'
  
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $SourcesDirectory = $(Build.SourcesDirectory)
      $apikey = $(apikey)
      mkdir "$SourcesDirectory/GuestConfigurationProject"
      
      mkdir "$SourcesDirectory/GuestConfigurationProject/editor"
      mkdir "$SourcesDirectory/GuestConfigurationProject/editor/VSCode"
      copy "$SourcesDirectory/editor/VSCode/settings.json" "$SourcesDirectory/GuestConfigurationProject/editor/VSCode/settings.json"
      copy "$SourcesDirectory/editor/VSCode/tasks.json" "$SourcesDirectory/GuestConfigurationProject/editor/VSCode/tasks.json"
      
      mkdir "$SourcesDirectory/GuestConfigurationProject/Modules"
      mkdir "$SourcesDirectory/GuestConfigurationProject/Modules/Module" 
      mkdir "$SourcesDirectory/GuestConfigurationProject/Modules/Module/DSCResources"
      mkdir "$SourcesDirectory/GuestConfigurationProject/Modules/Module/DSCResources/Resource"
      copy "$SourcesDirectory/Modules/Module/DSCResources/Resource/Resource.psm1" "$SourcesDirectory/GuestConfigurationProject/Modules//Module/DSCResources/Resource/Resource.psm1"
      copy "$SourcesDirectory/Modules/Module/DSCResources/Resource/Resource.schema.mof" "$SourcesDirectory/GuestConfigurationProject/Modules/Module/DSCResources/Resource/Resource.schema.mof"
      
      mkdir "$SourcesDirectory/GuestConfigurationProject/test"
      copy "$SourcesDirectory/test/Resource.Tests.ps1" "$SourcesDirectory/GuestConfigurationProject/test/Resource.Tests.ps1"
      
      copy "$SourcesDirectory/Configuration.mof" "$SourcesDirectory/GuestConfigurationProject/Configuration.mof"
      copy "$SourcesDirectory/GuestConfigurationProject.psd1" "$SourcesDirectory/GuestConfigurationProject/GuestConfigurationProject.psd1"
      copy "$SourcesDirectory/LICENSE" "$SourcesDirectory/GuestConfigurationProject/LICENSE"
      copy "$SourcesDirectory/plasterManifest.xml" "$SourcesDirectory/GuestConfigurationProject/plasterManifest.xml"
      copy "$SourcesDirectory/project.code-workspace" "$SourcesDirectory/GuestConfigurationProject/project.code-workspace"

      $params = @{
        Path        = $SourcesDirectory
        NuGetApiKey = $apikey
      }
      Get-ChildItem "$SourcesDirectory/GuestConfigurationProject/" -recurse
      
      Publish-Module @params
    pwsh: true
  displayName: 'Publish to Gallery'
