pool: 
  vmImage: 'windows-2019'

pr: none
  
trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - azure-pipelines.yml
    - README.md
    - CODE_OF_CONDUCT.md
    - SECURITY.md
    - LICENSE
    - .gitignore
    - .github/*
    - package
    - scratch.*

steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
        $powerShellPath = Join-Path -Path $env:AGENT_TEMPDIRECTORY -ChildPath 'powershell'
        Invoke-WebRequest -Uri https://raw.githubusercontent.com/PowerShell/PowerShell/master/tools/install-powershell.ps1 -outfile ./install-powershell.ps1
        ./install-powershell.ps1 -Destination $powerShellPath -Preview
        $vstsCommandString = "vso[task.setvariable variable=PATH]$powerShellPath;$env:PATH"
        Write-Host "sending " + $vstsCommandString
        Write-Host "##$vstsCommandString"
    pwsh: false
  displayName: Install PowerShell Core

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Install-PackageProvider -Name NuGet -RequiredVersion 2.8.5.201 -Force
      Install-Module Plaster,Pester,GuestConfiguration -force
    pwsh: true
  displayName: 'Install required modules'
  
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $params = @{
        Path        = '$(Build.SourcesDirectory)\GuestConfigurationProject'
        NuGetApiKey = '$(apikey)'
      }
      $publish = Publish-Module @params
      $publish | get-member
    pwsh: true
  displayName: 'Publish to Gallery'
